---

- name: Check composer
  stat:
    path: /usr/local/bin/composer
  register: composer_stat

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: composer_stat.stat.exists == false

- name: Run Composer installer
  command: php composer-installer.php
  args:
    chdir: /tmp
  when: composer_stat.stat.exists == false

- name: Move Composer into globally-accessible location.
  shell: mv /tmp/composer.phar /usr/local/bin/composer
  become: true
  when: composer_stat.stat.exists == false
