---

- name: Tap PHP homebrew
  homebrew_tap:
    name: "{{ item }}"
  with_items:
    - "homebrew/dupes"
    - "homebrew/versions"
    - "homebrew/homebrew-php"

- name: Install PHP
  homebrew:
    name: php71
    install_options: --with-fpm

- name: PHP ini settings
  lineinfile:
    dest: "{{ item[0] }}"
    regexp: "^{{ item[1].name }} ="
    line: "{{ item[1].name }} = {{ item[1].value }}"
  with_nested:
    - "{{ php.ini_files }}"
    - "{{ php.ini_settings }}"
  become: true


- include: composer.yml

- name: Copy Xdebug ini
  copy:
    src: "templates/ext-xdebug.ini"
    dest: "/usr/local/etc/php/7.1/conf.d/ext-xdebug.ini"

- name: Install Xdebug
  homebrew:
    name: php71-xdebug

- name: Install MySQL
  homebrew:
    name: mysql

- name: Install nginx
  homebrew:
    name: nginx

- name: Set nginx plist permissions
  shell: "{{ item }}"
  with_items:
    - "cp /usr/local/opt/nginx/*.plist /Library/LaunchDaemons"
    - "launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.nginx.plist"
  become: true

- name: Autostart MySQL, PHP-FPM
  shell: "brew services start {{ item }}"
  with_items:
    - "mysql"
    - "nginx"
    - "php71"
