---

-
  hosts: localhost
  roles:
    - virtual-hosts

  pre_tasks:
    - include_vars: "sites.yml"
      ignore_errors: true

  post_tasks:
    - name: Restart nginx
      shell: "{{ item }}"
      with_items:
        - "brew services restart php{{ config.php_version_short }}"
        - "nginx -s reload || nginx"
      become: true
