---

config:
  php_version_long: 7.1
  php_version_short: 71

php:
  ini_files:
      - "/usr/local/etc/php/{{ config.php_version_long }}/php.ini"

  ini_settings:
    - name: "memory_limit"
      value: "2048M"
    - name: "date.timezone"
      value: "Europe/Berlin"
    - name: "max_execution_time"
      value: "300"
    - name: "phar.readonly"
      value: "0"
