---

php:
  ini_files:
      - "/usr/local/etc/php/7.1/php.ini"

  ini_settings:
    - name: "memory_limit"
      value: "2048M"
    - name: "date.timezone"
      value: "Europe/Berlin"
    - name: "max_execution_time"
      value: "300"
