---

- find:
    paths: /usr/local/etc/nginx/servers
    file_type: file
    patterns: "*.conf"
  register: old_config_files

- name: Clear old configuration files
  file:
    path: "{{ item.path }}"
    state: "absent"
  with_items: "{{ old_config_files.files }}"

- name: Copy virtual host config
  template:
    src: "templates/host.conf.j2"
    dest: "/usr/local/etc/nginx/servers/{{ item.name }}.conf"
  with_items:
    - "{{ sites }}"
    - name: "info"
  when:
      - "item"
      - "item.config is undefined"

- name: Copy virtual host custom config
  template:
    src: "../../server-config/{{ item.config }}.conf.j2"
    dest: "/usr/local/etc/nginx/servers/{{ item.name }}.conf"
  with_items:
    - "{{ sites }}"
  when:
      - "item"
      - "item.config is defined"

- name: Create info directory
  file:
    path: "{{ sites_path }}/info"
    state: "directory"

- name: Add info virtual host
  copy:
    src: "templates/info.php"
    dest: "{{ sites_path }}/info/index.php"
